theme: minima
title: Iwilare
author: Andrea Laretto
email: iwilare@gmail.com
description: >
  Personal blog about programming, mathematics, philosophy.

title: iwilare
minima:
  date_format: "%Y-%m-%d"
  header_pages:
    - projects.md
  social_links:
    twitter: iwilare
    github: iwilare
    instagram: iwilare
    telegram: iwilare
    rss: rss
